# Generated by Django 5.2.7 on 2025-11-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(choices=[('90m', '90 Meter'), ('180m', '180 Meter')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(choices=[('2mp', '2MP'), ('2mp_color', '2MP Color'), ('5mp', '5MP'), ('5mp_color', '5MP Color')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.CharField(choices=[('4ch', '4 CH'), ('8ch', '8 CH'), ('16ch', '16 CH'), ('32ch', '32 CH')], max_length=10)),
                ('resolution', models.CharField(choices=[('2mp', '2MP'), ('5mp', '5MP')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Installation', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_slug', models.CharField(choices=[('1-4', '1–4 Cameras'), ('4-8', '4–8 Cameras'), ('8-16', '8–16 Cameras'), ('16-32', '16–32 Cameras')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('camera_qty', models.PositiveIntegerField(default=2)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bnc_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bnc_in_combo', to='home.accessory')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cable')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.camera')),
                ('dc_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_in_combo', to='home.accessory')),
                ('dvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dvr')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.installationcharge')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.powersupply')),
            ],
        ),
    ]
