# Generated by Django 5.2.7 on 2025-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_order_address_remove_order_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
