# Generated by Django 5.2.7 on 2025-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comboproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
