# Generated by Django 5.2.7 on 2025-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='bnc_qty',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='cable_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='dc_qty',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='installation_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='power_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
