# Generated by Django 5.2.7 on 2025-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comboproduct_bnc_qty_comboproduct_cable_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=100)),
            ],
        ),
    ]
