# Generated by Django 5.2.7 on 2025-11-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_harddisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='hard_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.harddisk'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='hard_disk_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
