# Generated by Django 5.2.7 on 2025-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_comboproduct_hard_disk_comboproduct_hard_disk_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harddisk',
            old_name='capacity',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='harddisk',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='harddisk',
            name='model_number',
        ),
        migrations.AddField(
            model_name='harddisk',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
