# Generated by Django 5.2.7 on 2025-11-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_capacity_harddisk_size_remove_harddisk_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboproduct',
            name='hard_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.harddisk'),
        ),
    ]
