# Generated by Django 5.2.7 on 2025-12-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('maintenance', 'Maintenance')], max_length=50),
        ),
    ]
