# Generated by Django 5.2.7 on 2025-12-01 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_servicebooking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_date',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
