# Generated by Django 5.2.7 on 2025-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_servicebooking_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_charge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('maintenance', 'Maintenance'), ('camera_upgrade', 'Camera Upgrade'), ('dvr_installation', 'DVR Installation')], max_length=50),
        ),
    ]
