# Generated by Django 5.2.7 on 2025-12-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_servicebooking_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
