# Generated by Django 5.2.7 on 2025-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_servicebooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.CharField(help_text='e.g. 2 Years, 5 Years', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('certified', models.BooleanField(default=False, help_text='Are you a certified CCTV technician?')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
