# Generated by Django 5.2.7 on 2025-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cctvengineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvengineer',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cctvengineer',
            name='experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cctvengineer',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
