# Generated by Django 5.2.7 on 2025-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_cctvengineer_certified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvengineer',
            name='certified',
            field=models.BooleanField(default=False, help_text='Are you a certified CCTV technician?'),
        ),
        migrations.AlterField(
            model_name='cctvengineer',
            name='experience',
            field=models.CharField(help_text='e.g. 2 Years, 5 Years', max_length=50),
        ),
    ]
