# Generated by Django 5.2.7 on 2025-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_cctvengineer_certified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvengineer',
            name='government_id',
            field=models.FileField(default='null', upload_to='engineer_ids/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cctvengineer',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cctvengineer',
            name='experience',
            field=models.CharField(max_length=50),
        ),
    ]
