# Generated by Django 5.2.7 on 2025-12-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_cctvengineer_government_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvengineer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('hold', 'Hold')], default='pending', max_length=20),
        ),
    ]
