# Generated by Django 5.2.7 on 2025-12-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_cctvengineer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(max_length=30),
        ),
    ]
