# Generated by Django 5.2.7 on 2025-12-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_camera_model_number_alter_camera_camera_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvr',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='dvr',
            name='resolution',
        ),
        migrations.AddField(
            model_name='dvr',
            name='dvr_name',
            field=models.CharField(default=1, help_text='Enter DVR name (e.g., CP Plus 8 Channel DVR)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvr',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
