# Generated by Django 5.2.7 on 2025-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_dvr_channels_remove_dvr_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='range_slug',
            field=models.CharField(max_length=100),
        ),
    ]
