# Generated by Django 5.2.7 on 2025-12-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_cable_length_alter_powersupply_range_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(max_length=100),
        ),
    ]
