# Generated by Django 5.2.7 on 2025-12-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_camerabullet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='camerabullet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.camerabullet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='camera_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
