# Generated by Django 5.2.7 on 2025-12-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_comboproduct_camerabullet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboproduct',
            name='camerabullet',
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='cameraBullet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.camerabullet'),
        ),
    ]
