# Generated by Django 5.2.7 on 2025-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_comboproduct_camerabullet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camerabullet',
            old_name='camera_type',
            new_name='bullet_camera_type',
        ),
        migrations.RenameField(
            model_name='camerabullet',
            old_name='model_number',
            new_name='bullet_model_number',
        ),
    ]
