# Generated by Django 5.2.7 on 2025-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_camera_type_camerabullet_bullet_camera_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='camerabullet_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='camera_qty',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
