# Generated by Django 5.2.7 on 2025-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_comboproduct_mrp_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
