# Generated by Django 5.2.7 on 2025-12-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_comboproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
