# Generated by Django 5.2.7 on 2025-12-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_comboproduct_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cable',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='camera',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='camerabullet',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dvr',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='harddisk',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='bnc_connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bnc_combo_products', to='home.accessory'),
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='dc_connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_combo_products', to='home.accessory'),
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='hard_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.harddisk'),
        ),
    ]
