# Generated by Django 5.2.7 on 2026-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_comboproduct_stock_accessory_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('cctvrepair', 'CCTV Repair'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
