# Generated by Django 5.2.7 on 2026-09-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_servicebooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='user',
        ),
    ]
