# Generated by Django 5.2.7 on 2026-09-25 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_servicebooking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accessory'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='bullet_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.camerabullet'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cable'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.camera'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.dvr'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='hard_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.harddisk'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='power_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.powersupply'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.accessory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bullet_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.camerabullet'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cable'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.camera'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dvr'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hard_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.harddisk'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='power_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.powersupply'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comboproduct'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.comboproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('cctvrepair', 'CCTV Repair Rs. 2000'), ('computerrepair', 'Computer Repair Rs. 1000')], default='cctvrepair', max_length=20),
        ),
    ]
