# Generated by Django 5.2.7 on 2026-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_cartitem_accessory_cartitem_bullet_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/accessories/'),
        ),
        migrations.AddField(
            model_name='cable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/cables/'),
        ),
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/cameras/'),
        ),
        migrations.AddField(
            model_name='camerabullet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/bullet_cameras/'),
        ),
        migrations.AddField(
            model_name='dvr',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/dvrs/'),
        ),
        migrations.AddField(
            model_name='harddisk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/hard_disks/'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/power_supplies/'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(help_text='Example: BNC Connector, DC Connector', max_length=100),
        ),
        migrations.AlterField(
            model_name='cable',
            name='length',
            field=models.CharField(help_text='Example: 90 Meter, 100 Meter', max_length=100),
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='size',
            field=models.CharField(help_text='Example: 1TB, 2TB, 4TB', max_length=50),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='range_slug',
            field=models.CharField(help_text='Example: 12V 2A, 12V 5A, 12V 10A', max_length=100),
        ),
    ]
